name: Main CI/CD Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Validate DAGs'
        uses: ./
        with:
          requirementsFile: tests/requirements.txt
          dagPaths: tests/dags
          pluginPaths: tests/plugins
          loadExamples: True
          varFile: tests/var.json
          connFile: tests/conns.json
          accessToken: ${{ secrets.GITHUB_TOKEN }}
